### ISSUE TITLE
文字

### ISSUE THREAD

**Issue by yanglegetuo** [11627685/easyofd-java#1]
<img width="699" alt="b9d9231ce39fef8aa797903dec221277" src="https://github.com/user-attachments/assets/a537d141-7fa5-4861-ac96-552b86666603">
在本地和另一条linux服务器是不重叠的，放到另外一台同版本操作系统的linux服务器出现了字符重叠

**Comment by 11627685** [comment]
参考：http://wiki.easyofd.cn/JAVA/%E6%96%87%E5%AD%97JAVA
七、关于字体的一些说明 最后一章节。应该是你的机子上的字体系统没有注册成功。可以通过下面程序验证。

GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] allFonts = ge.getAllFonts();
        List<String> chineseFonts = new ArrayList<>();

        for (Font font : allFonts) {

            System.out.println(font.getFontName());

//            // 检查字体名称是否包含中文字符
//            if (font.getName().matches(".*[\u4e00-\u9fa5]+.*")) {
//                chineseFonts.add(font.getFontName());
//            }
        }

        // 输出所有找到的中文字体名称
        for (String fontName : chineseFonts) {
            System.out.println(fontName);
        }
